// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using System.Linq;
using Microsoft.ML;
using CarPricePredictionML.Model;

namespace CarPricePredictionML.ConsoleApp
{
    class Program
    {
        //Dataset to use for predictions 
        private const string DATA_FILEPATH = @"C:\Work\GitHub\CarPricePrediction\CarPricePrediction\Datasets\GumTree2.csv";

        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = CreateSingleDataSample(DATA_FILEPATH);

            // Make a single prediction on the sample data and print results
            ModelOutput predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Price with predicted Price from sample data...\n\n");
            Console.WriteLine($"PriceType: {sampleData.PriceType}");
            Console.WriteLine($"SellerType: {sampleData.SellerType}");
            Console.WriteLine($"Make: {sampleData.Make}");
            Console.WriteLine($"Model: {sampleData.Model}");
            Console.WriteLine($"Variant: {sampleData.Variant}");
            Console.WriteLine($"BodyType: {sampleData.BodyType}");
            Console.WriteLine($"Year: {sampleData.Year}");
            Console.WriteLine($"Kilometers: {sampleData.Kilometers}");
            Console.WriteLine($"Trasmission: {sampleData.Trasmission}");
            Console.WriteLine($"DriveTrain: {sampleData.DriveTrain}");
            Console.WriteLine($"FuelType: {sampleData.FuelType}");
            Console.WriteLine($"Colour: {sampleData.Colour}");
            Console.WriteLine($"AirConditioning: {sampleData.AirConditioning}");
            Console.WriteLine($"ANCAPRating: {sampleData.ANCAPRating}");
            Console.WriteLine($"GreenStarRating: {sampleData.GreenStarRating}");
            Console.WriteLine($"CylinderConfigurationParsed: {sampleData.CylinderConfigurationParsed}");
            Console.WriteLine($"\n\nActual Price: {sampleData.Price} \nPredicted Price: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }

        // Change this code to create your own sample data
        #region CreateSingleDataSample
        // Method to load single row of dataset to try a single prediction
        private static ModelInput CreateSingleDataSample(string dataFilePath)
        {
            // Create MLContext
            MLContext mlContext = new MLContext();

            // Load dataset
            IDataView dataView = mlContext.Data.LoadFromTextFile<ModelInput>(
                                            path: dataFilePath,
                                            hasHeader: true,
                                            separatorChar: ',',
                                            allowQuoting: true,
                                            allowSparse: false);

            // Use first line of dataset as model input
            // You can replace this with new test data (hardcoded or from end-user application)
            ModelInput sampleForPrediction = mlContext.Data.CreateEnumerable<ModelInput>(dataView, false)
                                                                        .First();
            return sampleForPrediction;
        }
        #endregion
    }
}
