// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace CarPricePredictionML.Model
{
    public class ModelInput
    {
        [ColumnName("Price"), LoadColumn(0)]
        public float Price { get; set; }


        [ColumnName("PriceType"), LoadColumn(1)]
        public string PriceType { get; set; }


        [ColumnName("SellerType"), LoadColumn(2)]
        public string SellerType { get; set; }


        [ColumnName("Make"), LoadColumn(3)]
        public string Make { get; set; }


        [ColumnName("Model"), LoadColumn(4)]
        public string Model { get; set; }


        [ColumnName("Variant"), LoadColumn(5)]
        public string Variant { get; set; }


        [ColumnName("BodyType"), LoadColumn(6)]
        public string BodyType { get; set; }


        [ColumnName("Year"), LoadColumn(7)]
        public float Year { get; set; }


        [ColumnName("Kilometers"), LoadColumn(8)]
        public float Kilometers { get; set; }


        [ColumnName("Trasmission"), LoadColumn(9)]
        public string Trasmission { get; set; }


        [ColumnName("DriveTrain"), LoadColumn(10)]
        public string DriveTrain { get; set; }


        [ColumnName("FuelType"), LoadColumn(11)]
        public string FuelType { get; set; }


        [ColumnName("Colour"), LoadColumn(12)]
        public string Colour { get; set; }


        [ColumnName("AirConditioning"), LoadColumn(13)]
        public bool AirConditioning { get; set; }


        [ColumnName("ANCAPRating"), LoadColumn(14)]
        public float ANCAPRating { get; set; }


        [ColumnName("GreenStarRating"), LoadColumn(15)]
        public float GreenStarRating { get; set; }


        [ColumnName("CylinderConfigurationParsed"), LoadColumn(16)]
        public float CylinderConfigurationParsed { get; set; }


    }
}
